#ifndef __RotarySolidsMainFrame__
#define __RotarySolidsMainFrame__

/**
@file
Subclass of MainFrame, which is generated by wxFormBuilder.
*/

#include "RotarySolids.h"

//// end generated include

#include <wx/filedlg.h>
#include <wx/dcmemory.h>
#include <wx/dcclient.h>
#include <wx/dcbuffer.h>
#include <cmath>
#include <algorithm>
#include "vectorXD.h"
#include "matrixXD.h"
#include "Segment.h"
#include "RotarySolidsSelectionFrame.h"

enum class Shape { square, rectangle, triangle, circle, line, polygon, curve, sombrero, parabola };

/** Implementing MainFrame */
class RotarySolidsMainFrame : public MainFrame
{
	protected:
		// Handlers for MainFrame events.
		void LeftPanelOnLeftDClick( wxMouseEvent& event );
		void LeftPanelOnUpdateUI( wxUpdateUIEvent& event );
		void xLabelOnLeftDClick( wxMouseEvent& event );
		void xSliderUpdated( wxScrollEvent& event );
		void yLabelOnLeftDClick( wxMouseEvent& event );
		void ySliderUpdated( wxScrollEvent& event );
		void zLabelOnLeftDClick( wxMouseEvent& event );
		void zSliderUpdated( wxScrollEvent& event );
		void OpenPropertiesWindowButtonOnButtonClick( wxCommandEvent& event );
		void SaveToFileButtonOnButtonClick( wxCommandEvent& event );
		void ParallelProjectionButtonOnButtonClick( wxCommandEvent& event );
	public:
		/** Constructor */
		RotarySolidsMainFrame( wxWindow* parent );
	//// end generated class members

		// funkcja
		void Repaint();

		// funkcja generująca bazową figurę
		void generateShape();

		// funkcja rysująca bryłę jako wiele wypełnionych wielokątów
		void drawShape(wxBufferedDC&, int,  int);

		// funkcja pomocnicza rysująca osi Ox oraz Oy
		void drawAxis(wxBufferedDC&, int, int);

		// funkcje obracające bryłę wokół odpowiednich osi
		void rotateByXYZ();

		// funkcja generująca punkty bryły na podstawie punktów pierwszej figury leżącej na płaszczyźnie xOz
		void nextPoints(std::vector<Point>&);

		void circleNextPoints(std::vector<Point>&);

		// funkcja przeliczająca współrzędne x' i y' ze współrzędnych x, y i z
		wxPoint Point3DtoPoint2D(Point, int, int);

		void setNumOfContours(int);

		void setXCoord(int);

		void setZCoord(int);

		void setShape(Shape);

		void setDefaultSliders();

	private:

		wxImageHandler* imageHandler = nullptr;
		RotarySolidsSelectionFrame* propertiesFrame = NULL;
		Shape shape = Shape::square;
		std::vector<std::vector<Point>> data;
		std::vector<std::vector<Point>> dataWithoutRotation;
		int numOfContours = 0;
		double xCoord = 0;
		double zCoord = 0;
		int fileNum = 1;
};

#endif // __RotarySolidsMainFrame__
